### ISSUE TITLE
Add support for GET Bucket (List Objects) Version 2

### ISSUE THREAD

**Issue by fahrradflucht** [scality/cloudserver#1191]
The [official AWS API documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html) states that the version 1 of `GET Bucket (List Objects)` is only supported for legacy reasons. 

This leads me to use `GET Bucket (List Objects) Version 2`. Sadly testing against `s3server:mem-latest` with the `aws-sdk-js` indicates that it isn't supported by `scality/S3` yet because `getObjectsV2` always returns `null`.

**Comment by rahulreddy** [comment]
HI @fahrradflucht ,
AWS recently did the switch and we will be updating ours soon. You can still use V1 as it's still supported by all SDKs. I will add a `NotImplemented` header for this request to indicate that the feature is not supported.
Feel free to make a contribution for the feature if you have an idea for the implementation.

**Comment by baldychristophe** [comment]
Hi, 

Some libraries have already started to switch to the new API `GET Bucket (List Objects) Version 2` exclusively to make API calls (for instance the one I use https://github.com/jschneier/django-storages) which makes them incompatible with cloudserver.

Sadly, I don't know enough of nodejs to be of any use in helping you. I just want to draw your attention on this issue which may have been overlooked.

Thanks for your work

**Comment by smaffulli** [comment]
@baldychristophe @fahrradflucht  https://github.com/scality/cloudserver/pull/1559 added `GET Bucket (List Objects) Version 2` support.
