### ISSUE TITLE
InvalidAccessKeyId error

### ISSUE THREAD

**Issue by cloudinary-misha** [scality/cloudserver#1277]
Dear Zenko guys.

**The bug description**
I am trying to run S3 scality from shell , 
`aws s3 ls --endpoint-url=http://127.0.0.1:8000 --region us-east-1`
but always receive same error:
> An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS access key Id 
you provided does not exist in our records.

**My credentials setup:**
error reproduces with all of the following options:
1. **~/.aws/credentials**
[default]
aws_access_key_id=accessKey1
aws_secret_access_key=verySecretKey1

2. providing AWS VARIABLES in shell
`AWS_ACCESS_KEY_ID=accessKey1 AWS_SECRET_ACCESS_KEY=verySecretKey1 aws s3 ls --endpoint-url=http://127.0.0.1:8000 --region us-east-1`

3. `SCALITY_ACCESS_KEY_ID=newAccessKey SCALITY_SECRET_ACCESS_KEY=newSecretKey npm start`
and then trying 2 previous examples with 
newAccessKey
newSecretKey

Only when I rollback to commit id 95f458b9387a3cdbd5782b605f01487b561a62ee, error dissappears.
Current version of scality (with error) that I am trying to work with is:
Branch: development/8.0 
Commit id: 99d6f6f2a4dfc4f0e2d3ef4b82d238685ae14477

My setup:
OS: Ubuntu 16.04
Node: v6.14.2
Npm: 3.10.10
AWS cli - 1.15.31

I want to keep working with the latest version without need to work with particular commit id.

I will provide any required additional information.

Thanks in advance.

**Comment by rahulreddy** [comment]
Can you please try `REMOTE_MANAGEMENT_DISABLE=1 npm start` ?

**Comment by cloudinary-misha** [comment]
It worked for me, can you please explain what is it?
And be better if it will be added to README.
thanks

**Comment by rahulreddy** [comment]
Sure, we will do that.

**Comment by smaffulli** [comment]
Let's move this conversation to https://forum.zenko.io/t/how-to-avoid-issues-listing-buckets-with-aws-cli-1-6-15-and-later-versions/442

**Comment by Vishnu-yes-i-am** [comment]
> REMOTE_MANAGEMENT_DISABLE=1 npm start

thanks, It worked .I almost tired trying to figure out
