### ISSUE TITLE
problem in getting bucket size

### ISSUE THREAD

**Issue by siamackSeifi** [scality/cloudserver#1486]
Hi.

I am trying to save bucket size in my DB and update it every time object uploads or gets deleted so I don't have to calculate it in every request. So I get the size of data and add or subtract to bucket size in DB based on the operation(upload or delete).
Everything is fine when I upload files but when it comes to file deletion when I try to delete multiple files at the same time (bulk delete) the metadata of some of these objects are missing and i encounter {NoSuchKey: true}
This causes inconsistency in data as I delete some objects that I dont have their size so if for example I delete 200kb my bucket size substracts 150kb.
I tried to calculate bucketSize both in MongoClientInterface deleteObject and in lib/metadata/wrapper.js deleteObjectMD, but the result is the same.
Am I looking in the wrong place or is there any problem there?

**Comment by siamackSeifi** [comment]
Can anybody help me with this? Any ideas or suggestions?

**Comment by smaffulli** [comment]
@siamackSeifi which version of CloudServer are you using? How did you deploy your system? Please ask support requests on https://forum.zenko.io/
