### ISSUE TITLE
How to install an SSL certificate on each domain

### ISSUE THREAD

**Issue by siamackSeifi** [scality/cloudserver#1487]
Hi.

I am trying to install SSL certificate on each restEndpoints.
Is that possible on scality?

**Comment by rachedbenmustapha** [comment]
Hi @siamackSeifi - this would be possible by adding alternative names to the certificate that you are using. An example can be found [here](https://gist.github.com/croxton/ebfb5f3ac143cd86542788f972434c96).

**Comment by siamackSeifi** [comment]
Hi @RachedBenMustapha 
we have maybe more than 1000 hostnames which can't be handled with one cert.

**Comment by smaffulli** [comment]
@siamackSeifi could you please describe in more details your usecase on https://forum.zenko.io? We're better equipped at giving suggestions on deployments and operations there.
