### ISSUE TITLE
Problem in Starting Scality Server

### ISSUE THREAD

**Issue by siamackSeifi** [scality/cloudserver#1518]
Hi.

When I try to start the server I get the following error:

{"name":"S3","error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1",**"port":8900**},**"method":"_crrRequest"**,"time":1535890288941,"req_id":"fe2247bff1439d496c97","level":"error","message":"unable to perform request to backbeat api","hostname":"srv40286.screweb.com","pid":17679}
{"name":"S3","error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1",**"port":8900**},**"method":"getReplicationStates"**,"time":1535890288942,"req_id":"fe2247bff1439d496c97","level":"error","message":"unable to perform request to backbeat api","hostname":"srv40286.screweb.com","pid":17679}

Could you help me out?

Thanks.

**Comment by rachedbenmustapha** [comment]
Hi @siamackSeifi, if you re using cloudserver outside of the Zenko application stack, this error should not affect functionality. You can silence the errors by setting this environment variable: `REMOTE_MANAGEMENT_DISABLE=1`

**Comment by siamackSeifi** [comment]
Tnx @RachedBenMustapha
By setting this, the server started and I was able to create a new bucket.
But with more testing, I realized that multipart upload doesn't work. I don't know if there are more problems or not, but so far I encountered this.

**Comment by siamackSeifi** [comment]
Any update on this?
I still have problems and am using the last stable version I have.

**Comment by smaffulli** [comment]
@siamackSeifi which version do you have? You may want to ask on https://forum.zenko.io

**Comment by smaffulli** [comment]
I opened a thread on the forum to further discuss this issue. Please, join the conversation there @siamackSeifi  https://forum.zenko.io/t/how-to-avoid-issues-listing-buckets-with-aws-cli-1-6-15-and-later-versions/442
