### ISSUE TITLE
Trying to create an image with uploaded content

### ISSUE THREAD

**Issue by alexcocia** [scality/cloudserver#1552]
Hi all!
For CI purposes, I want to start an image with a set of data loaded in it, but also want to  be able to manipulate the content (adding / updating the files to be updated)
I can easily start the image with the data and metadata folders loaded, but that information is not easy to maintain. 
On the other hand, I have been trying to start the image and set some file contents on it using a client (s3cmd), but it doesn't work as the server is not "up and running" and the client cannot communicate with it.
My question is: 
Is there anyway to load the image with the content loaded?
PD: The only solution found so far (but still not valid for our purposes) is to have another docker to be used as a client

King regards,
Alex

**Comment by vrancurel** [comment]
Hello, one way to do it is to start an image with an empty data set, insert the data from the outside with s3cmd, then docker commit the image: it will generate a new docker image with the current content.

In order to do that you need to modify the Docker file to remove the VOLUMES lines (see the diff following):

```
diff --git a/Dockerfile b/Dockerfile
index 3f233bf8..286d773d 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -17,8 +17,6 @@ RUN apt-get update \
 
 COPY ./ ./
 
-VOLUME ["/usr/src/app/localData","/usr/src/app/localMetadata"]
-
 ENV NO_PROXY localhost,127.0.0.1
 ENV no_proxy localhost,127.0.0.1
```

Because Docker cannot commit paths marked as volumes then:

```
$ sudo docker build -t vrancurel/cloudserver:8.1-novol .
$ sudo docker run -it -p 8000:8000 -e REMOTE_MANAGEMENT_DISABLE=1 vrancurel/cloudserver:8.1-novol

```

From another terminal:

```
$ s3cmd ls
$ s3cmd mb s3://foo
Bucket 's3://foo/' created
$ s3cmd put /etc/hosts s3://foo
upload: '/etc/hosts' -> 's3://foo/hosts'  [1 of 1]
 338 of 338   100% in    0s     2.78 kB/s  done
$ sudo docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                                                     NAMES
b812f604c07f        vrancurel/cloudserver:8.1-novol   "/usr/src/app/docker…"   26 seconds ago      Up 25 seconds       0.0.0.0:8000->8000/tcp                                                                    festive_galileo
$ sudo docker commit b812f604c07f
sha256:6d8e03bd6c865013f185e8efcfcdf5a0b283c97f551cfb689106acd56e482785
```

Then stop the image and restart it with the new hash:

```
$ sudo docker run -it -p 8000:8000 -e REMOTE_MANAGEMENT_DISABLE=1 6d8e03bd6c86

```

From the other terminal, check that the data is indeed persisted:

```
$ s3cmd ls
2018-10-12 16:26  s3://foo
$ s3cmd get s3://foo/hosts
download: 's3://foo/hosts' -> './hosts'  [1 of 1]
 338 of 338   100% in    0s     4.60 kB/s  done
```

**Comment by alexcocia** [comment]
Hey Vrancurel!. Thanks for taking your time to answer the question...

In fact, this is more or less what we achieved, but required to modify the content some times, and therefore looking for a more flexible way for making it. 

Thanks anyway!
King regards,
Alex
