### ISSUE TITLE
s3 sync fails using awscli >= 1.16.15

### ISSUE THREAD

**Issue by troymolsberry** [scality/cloudserver#1561]
[this release of awscli](https://github.com/aws/aws-cli/commit/8b778dce8473c1b71acd364c4f0dcbdb5cfbc0c4) indicates that "s3 commands that list buckets will use ListObjectsV2". Indeed, when using awscli 1.16.15 or greater to s3 sync to scality s3server (deployed via docker), fails with exception 

fatal error: An error occurred (NotImplemented) when calling the ListObjectsV2 operation: A header you provided implies functionality that is not implemented.

awscli 1.16.14 or less will work.

**Comment by rrampr-zz** [comment]
I am running into the exact same issue

**Comment by mrozlukasz** [comment]
Yeah, having the same problem with `aws s3 cp`
current version `aws --version`
 `aws-cli/1.16.43 Python/2.7.15rc1 Linux/4.15.0-38-generic botocore/1.12.33`

Tried
`pip install awscli --upgrade --user`, no effect.

**Comment by JianqinWang** [comment]
Hi, I am assuming that everyone here is using the `scality/s3server` docker image, which is outdated.

Our current maintained image for this repo is here: https://hub.docker.com/r/zenko/cloudserver/

**Comment by smaffulli** [comment]
We should open a new issue and deprecate the scality/s3server image on Docker Hub, fix our docs so that people know to get zenko/cloudserver instead.

I'll write a summary of this conversation on https://forum.zenko.io

**Comment by smaffulli** [comment]
here it is. @JianqinWang @mrozlukasz @rrampr @jamesKyburz @troymolsberry please join the conversation on https://forum.zenko.io/t/how-to-avoid-issues-listing-buckets-with-aws-cli-1-6-15-and-later-versions/442

**Comment by JamesKyburz** [comment]
Thanks, all working now using the standalone run :)
