### ISSUE TITLE
Multiple errors after run npm install

### ISSUE THREAD

**Issue by denisgolius** [scality/cloudserver#1697]
[2019-02-01T15_34_38_215Z-debug.log](https://github.com/scality/cloudserver/files/2822225/2019-02-01T15_34_38_215Z-debug.log)

**Comment by philipyoo** [comment]
Hey @denisgolius , thanks for reporting this issue.

The leveldown module is a sub-dependency of one (or more) of cloudserver dependencies and unfortunately the sub-dependency (v1.6.0) does not work in some of the newer node.js versions. 

We are making attempts to update our dependencies, but for now, we recommend using node.js v8 LTS.

Please let us know if you still experience any other issues with the module installations

**Comment by denisgolius** [comment]
Ok, so what version of node.js is supported?

**Comment by philipyoo** [comment]
@denisgolius I believe any node LTS v8 should work. I've tried v8.9.0 and v8.15.0 and both seem to install modules just fine

**Comment by rahulreddy** [comment]
@denisgolius Were you able to install successfully?

**Comment by denisgolius** [comment]
I use minio server istead **scality/cloudserver**. But if it will be ported and modified to new node.js versions I will try it.
