### ISSUE TITLE
aws iam list-users command return `An error occurred (Unknown)`

### ISSUE THREAD

**Issue by toanddt** [scality/cloudserver#1837]
## Bug report information

I want to create some roles for my current users. And firstly, I tried using the command `aws iam list-users  --endpoint-url=http://example.com`. It returned error logs:

        An error occurred (Unknown) when calling the ListUsers operation: Unknown

I can use all `aws s3` command normally.

Does cloudserver support the behavior of `aws sts` and `aws iam` command?

**Comment by rahulreddy** [comment]
@toandd-vimentor Cloudserver hosts only S3 api, so you can only use `aws s3` or `aws s3api` commands. We don't have support for IAM/STS in Cloudserver.

**Comment by toanddt** [comment]
Thank you @rahulreddy

**Comment by rahulreddy** [comment]
@toandd-vimentor FYI, we have a commercial offering that provides IAM and STS to manage access to S3. If you are interested, please let me know I can get you in touch with the right people to explore your options. Here's the link to our website for more information https://www.scality.com
