### ISSUE TITLE
How to get http url of file object on cloud

### ISSUE THREAD

**Issue by tuandn8** [scality/cloudserver#2205]
I want to get url for file object in bucket as http protocol.

**Comment by smaffulli** [comment]
Hi @babytut I'm afraid I can't quite understand your question. Could you try explaining it a little more? maybe add the commands you've used and the output you're getting.

**Comment by tuandn8** [comment]
I have solved it. My question is: cloud server stores file objects with link like s3://<bucket_name>/<file_object> but I also want to have link like http://<hostname>/<bucket_name>/<file_object> 
I solved it by change acl of file object to public_read and use link pattern above. 
Can you give me best solution?

**Comment by dashagurova** [comment]
Hello @babytut, you are actually right about it, accessing the link by allowing public reads :)

**Comment by sunming2008** [comment]
@babytut Would you please tell me how to change acl of file object to public-read? many thanks.

**Comment by dashagurova** [comment]
Hello @sunming2008! Another great place to ask questions is on [Zenko forum](https://forum.zenko.io). Generally, you will get answers faster there from developers who maintain cloudserver.

**Comment by tuandn8** [comment]
> Hello @babytut, you are actually right about it, accessing the link by allowing public reads :)

My web client needs to access file to visualize data. The library which web client uses need access file as http url.

**Comment by dashagurova** [comment]
I see @babytut, let me check on this.

**Comment by dashagurova** [comment]
> @babytut Would you please tell me how to change acl of file object to public-read? many thanks.

@sunming2008 did you figure this out?

**Comment by tuandn8** [comment]
> > @babytut Would you please tell me how to change acl of file object to public-read? many thanks.
> 
> @sunming2008 did you figure this out?

yes, I change it by command s3cmd. But it may create some security issues. I want to find some better solutions.
