### ISSUE TITLE
the encryption method specified is not supported

### ISSUE THREAD

**Issue by yllihv27** [scality/cloudserver#2332]
I am trying to upload file to bucket using .Net S3 sdk.  I am receiving the encryption method specified is not supported ( Bad request  http code 400) 
my locationConstraint  type is file. We wanted to have offline storage servers thats why we use scality server on our on premise server .

**Comment by rahulreddy** [comment]
@yllihv27 Sorry I am looking at this late. Can you please capture and provide your request/response as well as the server side log in Cloudserver?

**Comment by yllihv27** [comment]
Hi creating encrypted bucket solved the issue.
Thanks

**Comment by rahulreddy** [comment]
Ah good to know, thank you!
